### ISSUE TITLE
php artisan migrate 5.0->5.1 maybe mariadb issue. how to fix ?

### ISSUE THREAD

**Issue by imgoodplanner** [cnvs/canvas#607]
Dear,

I try to 5.0 -> 5.1. when I run php artisan migrate, ... error 
How to fix ?

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'index `post_id` to `canvas_views_post_id_index`' at line 1 (SQL: alter table `canvas_views` rename index `post_id` to `canvas_views_post_id_index`)

**Comment by austintoddj** [comment]
Thanks for catching that @imgoodplanner. If you run `composer update` you should grab the latest version, `v5.1.1` which should fix the problem. 

Let me know if you need any more help with it.

**Comment by jswails** [comment]
hi, I just ran update and the issue still exists
Server version: 10.1.38-MariaDB-0ubuntu0.18.10.2 Ubuntu 18.10

- Updating cnvs/canvas (v5.0.3 => v5.1.1): Downloading (100%) 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MariaDB server  
   version for the right syntax to use near 'json null, `created_at` timestam  
  p null, `updated_at` timestamp null, `deleted_at' at line 1 (SQL: create ta  
  ble `canvas_posts` (`id` char(36) not null, `slug` varchar(191) not null, `  
  title` varchar(191) not null, `summary` text null, `body` text null, `publi  
  shed_at` datetime not null default '2018-10-12 00:00:00', `featured_image`   
  varchar(191) null, `featured_image_caption` varchar(191) null, `user_id` va  
  rchar(191) not null, `meta` json null, `created_at` timestamp null, `update  
  d_at` timestamp null, `deleted_at` timestamp null) default character set ut  
  f8mb4 collate 'utf8mb4_unicode_ci')                

i can just edit the migration file myself if you can point me to where its at please? I must be blind as I cant find it to edit it. Could be i am not familiar with this layout. Love this whole concept so would love to get it working. Appreciate it.

**Comment by austintoddj** [comment]
@jswails was this from a fresh install or an upgrade to an existing installation?

It looks like MariaDB started supporting JSON data types in [v10.2.*](https://mariadb.com/kb/en/json-data-type), so I'm assuming [this part of the migration](https://github.com/cnvs/canvas/blob/master/src/Storage/migrations/2018_10_12_000000_create_canvas_tables.php#L26) is causing the failure. 

Are you able to upgrade the MariaDB instance to 10.2 and give it another try?
